
name: flutter_app
description: back care test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  google_fonts: ^3.0.1
  analyzer: ^4.2.0
  intl: ^0.17.0
  nylo_framework: ^3.4.0
  woosignal: ^3.2.0
  flutter_stripe: ^6.0.0
  wp_json_api: ^3.2.0
  cached_network_image: ^3.2.2
  package_info: ^2.0.2
  money_formatter: ^0.0.3
  flutter_web_browser: ^0.17.1
  webview_flutter: ^3.0.4
  pull_to_refresh_flutter3: 2.0.1
  url_launcher: ^6.1.6
  flutter_styled_toast: ^2.1.3
  animate_do: ^2.1.0
  bubble_tab_indicator: ^0.1.5
  razorpay_flutter: ^1.3.4
  status_alert: ^1.0.1
  math_expressions: ^2.3.1
  validated: ^2.0.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  html: ^0.15.1
  flutter_widget_from_html_core: ^0.9.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_swiper_view: ^1.1.8
  firebase_messaging: ^14.0.3
  firebase_core: ^2.1.1
  convex_bottom_bar: ^3.1.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  collection: ^1.15.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

# APP ICON
flutter_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/appicon.png"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/
    - public/assets/json/
    - public/assets/images/
    - lang/
    - lang/ar.json
    - .env
